import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useState, useEffect} from 'react'
import hidden from '../app.config'

export default function Home() {
  const [flights, setFlights] = useState([])
  let allFlights = []

  const fetchFlights = () => {
    fetch('http://api.aviationstack.com/v1/flights?access_key=f7279e60689b13b0cf20867997c879a1')
    .then(res => res.json())
    .then(data => {
      allFlights.push(data.data)
      updateFlights(allFlights)
    })
    
  }

  const updateFlights = (flightsData) => {
    const departureTime = document.getElementById('departureTime')
    const arrivalTime = document.getElementById('arrivalTime')
    const departures = document.getElementById('departure')
    const arrivals = document.getElementById('arrival')
    const flightIds = document.getElementById('flightno')

    let departureTimeText = ''
    let arrivalTimeText = ''
    let departuresText = ''
    let arrivalsText = ''
    let flightIdsText = ''

    for(let i in flightsData[0]) {
      let flightTime = new Date(flightsData[0][i].departure.estimated)

      departureTimeText += `${flightTime.getHours().toString().padStart(2, '0')} : ${flightTime.getMinutes().toString().padStart(2, '0')}<br />`
      departuresText += `${flightsData[0][i].departure.iata}<br />`
      arrivalsText += `${flightsData[0][i].arrival.iata}<br />`
      flightIdsText += `${flightsData[0][i].flight.number}<br />`
    }

    departureTime.innerHTML = departureTimeText
    departures.innerHTML = departuresText
    arrivals.innerHTML = arrivalsText
    flightIds.innerHTML = flightIdsText
  }

  useEffect(() => {
    fetchFlights()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Planes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>The World of Planes</h1>

      <div className={styles.board}>
        <div id='departureTime' className={styles.col}>Loading</div>
        <div id='arrivalTime' className={styles.col}>Loading</div>
        <div id='departure' className={styles.col}>Loading</div>
        <div id='arrival' className={styles.col}>Loading</div>
        <div id='flightno' className={styles.col}>Loading</div>
      </div>
    </div>
  )
}
